//HintName: X.Module.g.cs
// <auto-generated />
using Autofac;
#nullable enable

partial class X : Bonus.SourceGen.IRegisterADelegateModule {
    public static Autofac.Core.IModule DelegateModule { get; } = new Module();
}

file class Module : Autofac.Module {
    protected override void Load(ContainerBuilder builder) {
        builder.Register<X.Void>(ctx => {
            var actual_delegate = X._();

            [System.Diagnostics.DebuggerStepThrough]
            void wrapped_with_histogram() {
                using var _ = Bonus.SourceGen.HistogramEntry.Record(X._histogram);
                actual_delegate();
            }

            [System.Diagnostics.DebuggerStepThrough]
            void wrapped_with_activity() {
                using var _ = X._activitySource.StartActivity("X.Void");
                wrapped_with_histogram();
            }

            return wrapped_with_activity;
        });
    }
}
