//HintName: DelegateShouldBeInternal.Module.g.cs
// <auto-generated />
using Autofac;
#nullable enable

namespace Bonus.SourceGen;

partial class DelegateShouldBeInternal : Bonus.SourceGen.IRegisterADelegateModule {
    public static Autofac.Core.IModule DelegateModule { get; } = new Module();
}

file class Module : Autofac.Module {
    protected override void Load(ContainerBuilder builder) {
        builder.Register<Bonus.SourceGen.DelegateShouldBeInternal.Void>(ctx => {
            var actual_delegate = Bonus.SourceGen.DelegateShouldBeInternal._();

            return actual_delegate;
        });
    }
}
