//HintName: Registrations.Module.g.cs
// <auto-generated />
using Autofac;
#nullable enable

namespace This.Place;

partial class Registrations {
    public static Autofac.Core.IModule DelegateModule { get; } = new Module();
}

file class Module : Autofac.Module {
    protected override void Load(ContainerBuilder builder) {
        builder.Register<This.Place.Registrations.GetTwo>(ctx => {
            var returnOne = ctx.Resolve<Somewhere.Else.ReturnOne>();

            var actual_delegate = This.Place.Registrations._(returnOne);

            return actual_delegate;
        });
    }
}
