//HintName: Registrations.Module.g.cs
// <auto-generated />
using Autofac;
#nullable enable

partial class Registrations {
    public static Autofac.Core.IModule DelegateModule { get; } = new Module();
}

file class Module : Autofac.Module {
    protected override void Load(ContainerBuilder builder) {
        builder.Register<GetFive>(ctx => {
            var actual_delegate = Registrations._();

            return actual_delegate;
        });
    }
}
