//HintName: Registrations.Module.g.cs
// <auto-generated />
using Autofac;
#nullable enable

namespace This.Place;

partial class Registrations {
    public static Autofac.Core.IModule DelegateModule { get; } = new Module();
}

file class Module : Autofac.Module {
    protected override void Load(ContainerBuilder builder) {
        builder.Register<This.Place.Registrations.GetFullNameLength>(ctx => {
            var actual_delegate = This.Place.Registrations._();

            [System.Diagnostics.DebuggerStepThrough]
            int wrapped_with_histogram(System.Type type) {
                using var _ = Bonus.SourceGen.HistogramEntry.Record(Metrics.MyHistogram);
                return actual_delegate(type);
            }

            return wrapped_with_histogram;
        });
    }
}
